remote_theme: pages-themes/hacker@v0.2.0
title: ESLint Plugin File Progress 2
description: ESLint Plugin File Progress 2 made by Typpi / Nick2bad4u
url: "https://nick2bad4u.github.io/eslint-plugin-file-progress-2/" # the base hostname & protocol for your site
plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-feed
    - jekyll-archives
    - jekyll-language-plugin
    - jekyll-algolia
    - jekyll-mentions
    - jekyll-admin
    - jekyll-loading-lazy
